import { useState } from 'react';
import { itinerary } from '../api/traveler';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { toast } from '../components/ui/use-toast';

interface DayPlan {
  day: number;
  title: string;
  blocks: { time: string; activity: string; location: string }[];
}

export default function ItineraryView() {
  const [userId, setUserId] = useState('demo-user');
  const [selectionId, setSelectionId] = useState('listing-123');
  const [nights, setNights] = useState(2);
  const [days, setDays] = useState<DayPlan[]>([]);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    setLoading(true);
    try {
      const response = await itinerary({ userId, selectionId, nights });
      setDays(response.days as DayPlan[]);
    } catch (error) {
      toast({
        title: 'Itinerary failed',
        description: (error as Error).message,
        variant: 'destructive'
      });
    } finally {
      setLoading(false);
    }
  };

  const downloadPdf = () => {
    window.print();
  };

  return (
    <div className="space-y-8">
      <div className="text-center space-y-2">
        <p className="text-xs uppercase tracking-[0.4em] text-brand-200">Itinerary</p>
        <h2 className="text-3xl font-semibold">Multi-day plan generated by Traveler Agent</h2>
        <p className="text-sm text-slate-300">
          Provide a selection and nights. Agent orchestrates embeddings + route heuristics locally.
        </p>
      </div>
      <div className="glass-panel grid gap-4 md:grid-cols-3">
        <div>
          <Label>User ID</Label>
          <Input className="mt-2" value={userId} onChange={(e) => setUserId(e.target.value)} />
        </div>
        <div>
          <Label>Selection ID</Label>
          <Input
            className="mt-2"
            value={selectionId}
            onChange={(e) => setSelectionId(e.target.value)}
          />
        </div>
        <div>
          <Label>Nights</Label>
          <Input
            type="number"
            className="mt-2"
            value={nights}
            onChange={(e) => setNights(Number(e.target.value))}
          />
        </div>
        <div className="md:col-span-3 flex gap-3">
          <Button onClick={generate} disabled={loading}>
            {loading ? 'Generating...' : 'Generate Itinerary'}
          </Button>
          <Button variant="secondary" onClick={downloadPdf}>
            Download PDF
          </Button>
        </div>
      </div>

      <div className="space-y-6">
        {days.map((day) => (
          <div key={day.day} className="glass-panel space-y-4 p-6">
            <div className="flex items-center justify-between">
              <h3 className="text-xl font-semibold">
                Day {day.day}: {day.title}
              </h3>
              <span className="text-xs uppercase tracking-widest text-slate-300">Local AI route</span>
            </div>
            <div className="space-y-3">
              {day.blocks.map((block) => (
                <div key={block.time} className="flex flex-col rounded-2xl border border-white/10 bg-slate-900/50 p-4 md:flex-row md:items-center md:justify-between">
                  <div className="text-brand-200">{block.time}</div>
                  <div>
                    <p className="font-semibold">{block.activity}</p>
                    <p className="text-xs text-slate-300">{block.location}</p>
                  </div>
                  <Button variant="ghost" size="sm">
                    Contact host
                  </Button>
                </div>
              ))}
            </div>
          </div>
        ))}
        {!days.length && <p className="text-center text-slate-400">Generate an itinerary to see the plan.</p>}
      </div>
    </div>
  );
}

